version: "2"

services:
  micromdm_bolt2mysql:
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    image: micromdm_bolt2mysql
    environment:
      MICROMDM_MYSQL_USER: micromdm
      MICROMDM_MYSQL_PASSWORD: micromdm
      MICROMDM_MYSQL_DATABASE: micromdm
      MICROMDM_MYSQL_HOST: me.home.local
      MICROMDM_MYSQL_PORT: 3306
    command: /go/src/github.com/micromdm/micromdm/micromdm_bolt2mysql
    volumes:
        - ./bolt_database:/tmp/
